In [1]:
#1 Suppose you have a dataset containing daily temperature readings for a city, and you want to identify days with extreme temperature conditions. Find days where the temperature either exceeded 35 degrees Celsius (hot day) or dropped below 5 degrees Celsius (cold day).
#Input:
#temperatures = p.array (32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2)


In [31]:
import numpy as np
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2])
hot_days = np.where(temperatures > 35)[0]
cold_days = np.where(temperatures < 5)[0]
print("Hot days:", hot_days,)
print("Cold days :", cold_days)


Hot days: [2 5 9]
Cold days : []


In [ ]:
#2 Suppose you have a dataset containing monthly sales data for a company, and you want to split this data into quarterly reports for analysis and reporting purposes.

#Input:

#monthly_sales = np.array([120, 135, 140, 165, 180, 155, 168, 190, 205, 198, 210, 225])


In [13]:
import numpy as np

monthly_sales = np.array([120, 135, 140, 165, 180, 155, 168, 190, 205, 198, 210, 225])
quarter1_sales = monthly_sales[:3]
quarter2_sales = monthly_sales[3:6]
quarter3_sales = monthly_sales[6:9]
quarter4_sales = monthly_sales[9:]
print("Quarter 1 Sales (in thousands of dollars):\n", quarter1_sales)
print("\nQuarter 2 Sales (in thousands of dollars)\n", quarter2_sales)
print("\nQuarter 3 Sales (in thousands of dollars):\n", quarter3_sales)
print("\nQuarter 4 Sales (in thousands of dollars)\n", quarter4_sales)

Quarter 1 Sales (in thousands of dollars):
 [120 135 140]

Quarter 2 Sales (in thousands of dollars)
 [165 180 155]

Quarter 3 Sales (in thousands of dollars):
 [168 190 205]

Quarter 4 Sales (in thousands of dollars)
 [198 210 225]


In [ ]:
#3 Suppose you have a dataset containing customer data, and you want to split this data into two groups: one group for customers who made a purchase in the last 30 days and another group for customers who haven't made a purchase in the last 30 days.
#Input:
#customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
#last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [15]:
import numpy as np
customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])
recent_customers = last_purchase_days_ago <= 30
non_recent_customers = last_purchase_days_ago > 30
recent_customer_ids = customer_ids[recent_customers]
non_recent_customer_ids = customer_ids[non_recent_customers]
print("Recent Customers:")
print(recent_customer_ids)
print("Non-Recent Customers:")
print(non_recent_customer_ids)

Recent Customers:
[101 102 103 104 105]
Non-Recent Customers:
[106 107 108 109 110]


In [16]:
#4.Suppose you have two sets of employee data—one containing information about
#full-time employees and another containing information about part-time employees. You
#want to combine this data to create a comprehensive employee dataset for HR analysis.
#Input:
# Employee data for full-time employees
#full_time_employees = np.array([
#[101, 'John Doe', 'Full-Time', 55000],
#[102, 'Jane Smith', 'Full-Time', 60000],
#[103, 'Mike Johnson', 'Full-Time', 52000])
# Employee data for part-time employees
#part_time_employees = np.array([
#[201, 'Alice Brown', 'Part-Time', 25000],
#[202, 'Bob Wilson', 'Part-Time', 28000],
#[203, 'Emily Davis', 'Part-Time', 22000]])


In [18]:
import numpy as np
full_time_employees = np.array([
    [101, 'John Doe', 'Full-Time', 55000],
    [102, 'Jane Smith', 'Full-Time', 60000],
    [103, 'Mike Johnson', 'Full-Time', 52000]
])
part_time_employees = np.array([
    [201, 'Alice Brown', 'Part-Time', 25000],
    [202, 'Bob Wilson', 'Part-Time', 28000],
    [203, 'Emily Davis', 'Part-Time', 22000]
])
all_employees = np.vstack((full_time_employees, part_time_employees))
print("Combined Employee Data:")
for employee in all_employees:
    print(f"Employee ID: {employee[0]}, Name: {employee[1]}, Type: {employee[2]}, Salary: {employee[3]}")

Combined Employee Data:
Employee ID: 101, Name: John Doe, Type: Full-Time, Salary: 55000
Employee ID: 102, Name: Jane Smith, Type: Full-Time, Salary: 60000
Employee ID: 103, Name: Mike Johnson, Type: Full-Time, Salary: 52000
Employee ID: 201, Name: Alice Brown, Type: Part-Time, Salary: 25000
Employee ID: 202, Name: Bob Wilson, Type: Part-Time, Salary: 28000
Employee ID: 203, Name: Emily Davis, Type: Part-Time, Salary: 22000


In [27]:
import numpy as np
list_of_arrays = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]
means = [np.mean(arr) for arr in list_of_arrays]

for i, mean in enumerate(means):
    print(f"Mean of array {i+1}: {mean}")


Mean of array 1: 5.5
Mean of array 2: 30.6
Mean of array 3: 34.0


In [30]:
import numpy as np

list_of_arrays = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]
means = [np.mean(arr) for arr in list_of_arrays]
print("Mean of Each array")
print(means)

Mean of Each array
[5.5, 30.6, 34.0]


In [1]:
#2. Compute the median of the flattened NumPy array
#Input: x_odd = np.array([1, 2, 3, 4, 5, 6, 7])

In [10]:
import numpy as np

x_odd = np.array([1, 2, 3, 4, 5, 6, 7])
median = np.median(x_odd)
print("printing the original array:")
print(x_odd)
print(" median of the array that contains odd no of elements:")
print(median)

printing the original array:
[1 2 3 4 5 6 7]
 median of the array that contains odd no of elements:
4.0


In [16]:
#3.Compute the standard deviation of the NumPy array
#Input: arr = [20, 2, 7, 1, 34]

In [15]:
import numpy as np
arr = np.array([20, 2, 7, 1, 34])
std_default = np.std(arr)
std_float32 = np.std(arr.astype(np.float32))
std_float64 = np.std(arr.astype(np.float64))

print(f"arr : {list(arr)}")
print(f"std of arr : {std_default:.15f}\n")
print(f"More precision with float32")
print("std of arr : {std_float32:.6f}\n")
print(f"More accuracy with float64")
print(f"std of arr : {std_float64:.15f}")


arr : [20, 2, 7, 1, 34]
std of arr : 12.576167937809991

More precision with float32
std of arr : {std_float32:.6f}

More accuracy with float64
std of arr : 12.576167937809991


In [ ]:
#4.