In [5]:
import numpy as np
l=[10,30,25,43,21]
arr=np.array(l)
print(arr)

[10 30 25 43 21]


In [11]:
import numpy as np
a=np.array(42)
b=np.array([1,2,2,3,4])
c= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])



print("a array",a)
print("b array",b)
print("c array",c)
print("d array",d)

print("a array dime",a.ndim)
print("b array dime",b.ndim)
print("c array dime",c.ndim)
print("d array dime",d.ndim)


a array 42
b array [1 2 2 3 4]
c array [[1 2 3]
 [4 5 6]
 [7 8 9]]
d array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
a array dime 0
b array dime 1
c array dime 2
d array dime 3


In [18]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
sarr=arr[1:5]
print(arr)
print(sarr)
sarr[2]=100
print(sarr)
print(arr)

[1 2 3 4 5 6 7]
[2 3 4 5]
[  2   3 100   5]
[  1   2   3 100   5   6   7]


In [20]:
#1. 1D array-vector
#2. 2D array-matrix
#3. 3D array-tensor

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [23]:
#The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

#The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [29]:
import numpy as np
a=np.zeros((6,2))
print(a)



[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [30]:
#numpy.zeros() in Python
#The numpy.zeros() function is one of the most significant functions which is used in machine learning programs widely. This function is used to  generate an array containing zeros.
#The numpy.zeros() function provide a new array of given shape and type, which is filled with zeros.

In [32]:
#numpy.zeros() without order
import numpy as np
a=np.zeros((6,),dtype=int)
print(a)

[0 0 0 0 0 0]


In [ ]:

#The NumPy ones() function in Python is used to create an array of the specified shape and type, where all the elements are set to 1. This function is very similar to zeros(). The ones () function takes three arguments and returns the array filled with value 1. In this article, I will explain how to use the NumPy ones() function with examples.

In [33]:
import numpy as np
a=np.ones((6,2))
print(a)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [35]:
import numpy as np
a=np.ones((6,2)) * 10
print(a)


[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]


In [37]:
import numpy as np
a=np.ones(5,dtype=int)
print(a)


[1 1 1 1 1]


In [38]:
import numpy as np
a=np.ones((6),dtype=int)
print(a)

[1 1 1 1 1 1]


In [39]:
import numpy as np
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:

#The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a Øk (default) is for the main diagonal.

In [42]:
import numpy as np
arr4=np.eye(7)
print(arr4)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#DIAGONAL

In [45]:
import numpy as np
arr=np.diag((3,4,1,6))
print(arr)
print(arr.ndim)
print(arr.shape)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 6]]
2
(4, 4)
